var secondsPerMin = 60;
var minsPerHour = 60;
var hoursPerDay = 24;
var daysPerWeek = 7;
var weeksPerYear = 52;
var secondsPerDay = secondsPerMin * minsPerHour * hoursPerDay;
document.write('<p>There are ' + secondsPerDay + ' seconds in a day</p>');
var yearsAlive = 27;
var secAlive = secondsPerDay * daysPerWeek * weeksPerYear * yearsAlive;
document.write("<p>I've been alive for more than " + secAlive + " seconds.</p>" );